Better handle database password issue at install time

diff --git a/modules/genoring/src/genoring/res/genoring b/modules/genoring/src/genoring/res/genoring
--- a/modules/genoring/src/genoring/res/genoring
+++ b/modules/genoring/src/genoring/res/genoring
@@ -34,8 +34,15 @@ setup_log="/opt/drupal/genoring_setup.log"
 # moment. This may change to 'stable", "RC", or "beta" in the future.
 # stability="stable"
 stability="dev"
-ENCODED_PG_PASSWORD=$(perl -e '$_=$ARGV[0];s/([^\w\s\Q.-~\E])/sprintf("%%%X",ord("$1"))/geix;print;' "$POSTGRES_PASSWORD")
-ESCAPED_DRUPAL_PASSWORD=$(perl -e 'print join("",map{/([\&\*\?\[\]\(\)\{\}\$\|\\\!;\'"'"'"])/?"\\$1":$_}split(//,$ARGV[0]))' "$DRUPAL_PASSWORD")
+forbidden_password_chars='#$%"\/:?@'
+if echo "$POSTGRES_PASSWORD" | grep -q "[$forbidden_password_chars]"; then
+  printf "WARNING: invalid characters ($forbidden_password_chars) found in the PostgreSQL password environment variable POSTGRES_PASSWORD! Installation will FAIL!\n" >&2
+  printf "WARNING: invalid characters found in the PostgreSQL password environment variable POSTGRES_PASSWORD\nPOSTGRES_PASSWORD: $POSTGRES_PASSWORD\nInvalid characters: $forbidden_password_chars\n" >>"$setup_log"
+fi
+
+# Escape password for use in shell/URI (escape backslashes, double quotes and dollar signs).
+ESCAPED_PG_PASSWORD=$(perl -e '$_=shift; s/\\/\\\\/g; s/"/\\"/g; s/\$/\\\$/g; print $_' "$POSTGRES_PASSWORD")
+ESCAPED_DRUPAL_PASSWORD=$(perl -e 'print join("",map{/([\&\*\?\[\]\(\)\{\}\$\|\\\!;\'"'"'\"])/?"\\$1":$_}split(//,$ARGV[0]))' "$DRUPAL_PASSWORD")
 
 
 
@@ -281,13 +288,13 @@ setup_cms()
   printf -- "--------------------------------------------------------------------------------\nDefault site directory:\n-----------------------\n" >>"$setup_log"
   ls -la /opt/drupal/web/sites/default >>"$setup_log"
   printf -- "--------------------------------------------------------------------------------\n\n" >>"$setup_log"
-  printf "Drush command: drush -y site:install recipes/genoring_recipe --db-url=\"pgsql://$POSTGRES_USER:$ENCODED_PG_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DRUPAL_DB\" --account-mail=\"$DRUPAL_USER_MAIL\" --account-name=\"$DRUPAL_USER\" --account-pass=\"$DRUPAL_PASSWORD\" --site-mail=\"$DRUPAL_SITE_MAIL\" --site-name=\"$DRUPAL_SITE_NAME\"\n\n" >>"$setup_log"
+  printf "Drush command: drush -y site:install recipes/genoring_recipe --db-url=\"pgsql://$POSTGRES_USER:$ESCAPED_PG_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DRUPAL_DB\" --account-mail=\"$DRUPAL_USER_MAIL\" --account-name=\"$DRUPAL_USER\" --account-pass=\"$DRUPAL_PASSWORD\" --site-mail=\"$DRUPAL_SITE_MAIL\" --site-name=\"$DRUPAL_SITE_NAME\"\n\n" >>"$setup_log"
   # For Drupal install debugging:
   # printf "DEBUG\n"; while :; do sleep 60; done
   {
     stdbuf -oL -eL \
     drush -y site:install recipes/genoring_recipe \
-      --db-url="pgsql://$POSTGRES_USER:$ENCODED_PG_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DRUPAL_DB" \
+      --db-url="pgsql://$POSTGRES_USER:$ESCAPED_PG_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DRUPAL_DB" \
       --account-mail="$DRUPAL_USER_MAIL" \
       --account-name="$DRUPAL_USER" \
       --account-pass="$DRUPAL_PASSWORD" \
@@ -296,7 +303,7 @@ setup_cms()
   } >>"$setup_log"
   if [ $? -gt 0 ]; then
     log "  ...ERROR!"
-    log_error "ERROR: Failed to initialize Drupal!\npgsql://$POSTGRES_USER:$ENCODED_PG_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DRUPAL_DB"
+    log_error "ERROR: Failed to initialize Drupal!\npgsql://$POSTGRES_USER:$ESCAPED_PG_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DRUPAL_DB"
     exit 1
   fi
   log "  ...OK (Drupal initialized)."
@@ -462,7 +469,7 @@ inittest()
     cp web/core/phpunit.xml.dist "$PHPUNIT_FILE"
     chown genoring:genoring web/core/phpunit.xml
     perl -pi -e 's|<env name="SIMPLETEST_BASE_URL".*?>|<env name="SIMPLETEST_BASE_URL" value="http://genoring-proxy"/>|' "$PHPUNIT_FILE"
-    perl -pi -e "s|<env name=\"SIMPLETEST_DB\".*?>|<env name=\"SIMPLETEST_DB\" value=\"pgsql://$POSTGRES_USER:$ENCODED_PG_PASSWORD\@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DRUPAL_DB\"/>|" "$PHPUNIT_FILE"
+    perl -pi -e "s|<env name=\"SIMPLETEST_DB\".*?>|<env name=\"SIMPLETEST_DB\" value=\"pgsql://$POSTGRES_USER:$ESCAPED_PG_PASSWORD\@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DRUPAL_DB\"/>|" "$PHPUNIT_FILE"
     perl -pi -e 's|<env name="BROWSERTEST_OUTPUT_DIRECTORY".*?>||' "$PHPUNIT_FILE"
     perl -pi -e "s|<env name=\"BROWSERTEST_OUTPUT_BASE_URL\".*?>|<env name=\"BROWSERTEST_OUTPUT_BASE_URL\" value=\"http://$GENORING_HOST:$GENORING_PORT\"/>\n    <env name=\"BROWSERTEST_OUTPUT_DIRECTORY\" value=\"/opt/drupal/web/sites/simpletest/browser_output\"/>|" "$PHPUNIT_FILE"
   fi
@@ -707,11 +714,12 @@ Available commands:
 ################################################################################
 
 # PostgeSQL access setup.
-printf "$POSTGRES_HOST:$POSTGRES_PORT:*:$POSTGRES_USER:$POSTGRES_PASSWORD\n" >~/.pgpass && chmod go-rwx ~/.pgpass
+printf "$POSTGRES_HOST:$POSTGRES_PORT:*:$POSTGRES_USER:$ESCAPED_PG_PASSWORD\n" >~/.pgpass
+chmod go-rwx ~/.pgpass
 
 # Process commands.
 cmd="$1"
-shift
+shift  2>/dev/null
 printf "COMMAND: $cmd\n" >>"$setup_log"
 case "$cmd" in
   start)
