Refactoring on Genrogin core script

diff --git a/modules/genoring/src/genoring/res/genoring b/modules/genoring/src/genoring/res/genoring
--- a/modules/genoring/src/genoring/res/genoring
+++ b/modules/genoring/src/genoring/res/genoring
@@ -275,9 +275,19 @@ start_genoring()
   service sendmail start
   printf "  ...OK.\n"
 
+  # Make sure we removed offline file if not in offline mode.
+  if [ -z $COMPOSE_PROFILES ] || [ $COMPOSE_PROFILES != 'offline' ]; then
+    if [ -e ./web/offline.html ]; then
+      rm -f ./web/offline.html
+    fi
+  fi
+
   printf "* Running PHP-fpm daemon...\n"
-  # Launch PHP-fpm
-  php-fpm
+  # Launch PHP-fpm in foreground. We use exec to use the keep the script process
+  # ID (PID 1) to be able to receive signals such as SIGTERM or SIGKILL.
+  # Ortherwise, the container will be killed by Docker instead of stopping
+  # gracefully.
+  exec php-fpm -F
   # We should not get there.
   printf "[Stopped]\n"
 }
@@ -324,37 +334,15 @@ uninstall_module()
 add_menuitem()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: add_menuitem(): Missing menu URI!"
+    >&2 printf "ERROR: add_menuitem(): Missing YAML file!"
     exit 1
   fi
-
-  # Check URL type.
-  case $1 in
-    http*)
-      menu_item_uri="$1"
-      ;;
-
-    /*)
-      menu_item_uri="internal:$1"
-      ;;
-
-    *)
-      menu_item_uri="internal:/$1"
-      ;;
-  esac
-
-  if [ -z "$2" ]; then
-    >&2 printf "ERROR: add_menuitem(): Missing menu label!"
-    exit 1
-  fi
-
-  # Machine name of the menu holding the menu item.
-  menu_name="${3:-main}"
 
   # Add menu item if not exist.
-  drush php:eval "use Drupal\\menu_link_content\\Entity\\MenuLinkContent; if (empty(\\Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['link.uri' => '$menu_item_uri']))) {MenuLinkContent::create(['title' => '$2', 'link' => ['uri' => '$menu_item_uri'], 'menu_name' => '$menu_name', 'expanded' => TRUE])->save();}"
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_menuitem $1
+
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to add menu item '$2'!\n"
+    >&2 printf "ERROR: Failed to add menu item using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -362,48 +350,95 @@ add_menuitem()
 remove_menuitem()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: add_menuitem(): Missing menu URI!"
+    >&2 printf "ERROR: remove_menuitem(): Missing YAML file!"
     exit 1
   fi
 
-  # Check URL type.
-  case $1 in
-    http*)
-      menu_item_uri="$1"
-      ;;
+  # Remove menu items.
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_menuitem $1
 
-    /*)
-      menu_item_uri="internal:$1"
-      ;;
+  if [ $? -gt 0 ]; then
+    >&2 printf "ERROR: Failed to remove menu item using YAML file '$1'!\n"
+    exit 1
+  fi
+}
 
-    *)
-      menu_item_uri="internal:/$1"
-      ;;
-  esac
+add_page()
+{
+  if [ -z "$1" ]; then
+    >&2 printf "ERROR: add_page(): Missing YAML file!"
+    exit 1
+  fi
+
+  # Add page.
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_page $1
+
+  if [ $? -gt 0 ]; then
+    >&2 printf "ERROR: Failed to add page using YAML file '$1'!\n"
+    exit 1
+  fi
+}
+
+remove_page()
+{
+  if [ -z "$1" ]; then
+    >&2 printf "ERROR: remove_page(): Missing YAML file!"
+    exit 1
+  fi
 
   # Remove menu items.
-  drush php:eval "foreach (\\Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['link.uri' => '$menu_item_uri']) as \$mi) {\$mi->delete();}"
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_page $1
+
+  if [ $? -gt 0 ]; then
+    >&2 printf "ERROR: Failed to remove page using YAML file '$1'!\n"
+    exit 1
+  fi
+}
+
+add_integration()
+{
+  if [ -z "$1" ]; then
+    >&2 printf "ERROR: add_integration(): Missing YAML file!"
+    exit 1
+  fi
+
+  # Add integration.
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_integration $1
+
+  if [ $? -gt 0 ]; then
+    >&2 printf "ERROR: Failed to add integration using YAML file '$1'!\n"
+    exit 1
+  fi
+}
+
+remove_integration()
+{
+  if [ -z "$1" ]; then
+    >&2 printf "ERROR: remove_integration(): Missing YAML file!"
+    exit 1
+  fi
+
+  # Remove integration.
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_integration $1
+
+  if [ $? -gt 0 ]; then
+    >&2 printf "ERROR: Failed to remove integration using YAML file '$1'!\n"
+    exit 1
+  fi
 }
 
 add_user()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: add_user(): Missing user name!"
+    >&2 printf "ERROR: add_user(): Missing YAML file!"
     exit 1
   fi
 
-  if [ -z "$2" ]; then
-    >&2 printf "ERROR: add_user(): Missing user e-mail!"
-    exit 1
-  fi
+  # Add user.
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_user $1
 
-  # Make sure we got a default user password.
-  user_password="${3:-Drupal1234!}"
-
-  # Create user.
-  drush user:create "$1" --mail="$2" --password="$user_password"
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to create user '$1'!\n"
+    >&2 printf "ERROR: Failed to add user using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -411,14 +446,15 @@ add_user()
 remove_user()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: remove_user(): Missing user name!"
+    >&2 printf "ERROR: remove_user(): Missing YAML file!"
     exit 1
   fi
 
   # Remove user.
-  drush user:cancel --reassign-content "$1"
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_user $1
+
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to remove user '$1'!\n"
+    >&2 printf "ERROR: Failed to remove user using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -426,12 +462,15 @@ remove_user()
 add_group()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: add_group(): Missing group name!"
+    >&2 printf "ERROR: add_group(): Missing YAML file!"
     exit 1
   fi
-  drush role:create "$1"
+
+  # Add group.
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_group $1
+
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to create group '$1'!\n"
+    >&2 printf "ERROR: Failed to add group using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -439,50 +478,47 @@ add_group()
 remove_group()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: remove_group(): Missing group name!"
+    >&2 printf "ERROR: remove_group(): Missing YAML file!"
     exit 1
   fi
-  drush role:delete "$1"
+
+  # Remove group.
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_group $1
+
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to remove group '$1'!\n"
+    >&2 printf "ERROR: Failed to remove group using YAML file '$1'!\n"
     exit 1
   fi
 }
 
 add_user_to_group()
 {
-  if [ -z "$2" ]; then
-    >&2 printf "ERROR: add_user_to_group(): Missing group name!"
-    exit 1
-  fi
-
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: add_user_to_group(): Missing user name!"
+    >&2 printf "ERROR: add_user_to_group(): Missing YAML file!"
     exit 1
   fi
 
-  drush user:role:add "$2" "$1"
+  # Add user to group.
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_user_to_group $1
+
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to add user '$1' to group '$2'!\n"
+    >&2 printf "ERROR: Failed to add user to group using YAML file '$1'!\n"
     exit 1
   fi
 }
 
 remove_user_from_group()
 {
-  if [ -z "$2" ]; then
-    >&2 printf "ERROR: remove_user_from_group(): Missing group name!"
-    exit 1
-  fi
-
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: remove_user_from_group(): Missing user name!"
+    >&2 printf "ERROR: remove_user_from_group(): Missing YAML file!"
     exit 1
   fi
 
-  drush user:role:remove "$2" "$1"
+  # Add user to group.
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_user_from_group $1
+
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to remove user '$1' from group '$2'!\n"
+    >&2 printf "ERROR: Failed to remove user from group using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -490,18 +526,15 @@ remove_user_from_group()
 add_permission()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: add_permission(): Missing permission name!"
+    >&2 printf "ERROR: add_permission(): Missing YAML file!"
     exit 1
   fi
 
-  if [ -z "$2" ]; then
-    >&2 printf "ERROR: add_permission(): Missing group name!"
-    exit 1
-  fi
+  # Add permission to group.
+  drush php:script --script-path=/opt/genoring/lib genoringapi add_permission $1
 
-  drush role:perm:add "$1" "$2"
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to add permission '$1' to group '$2'!\n"
+    >&2 printf "ERROR: Failed to add permission using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -509,18 +542,15 @@ add_permission()
 remove_permission()
 {
   if [ -z "$1" ]; then
-    >&2 printf "ERROR: remove_permission(): Missing permission name!"
+    >&2 printf "ERROR: add_permission(): Missing YAML file!"
     exit 1
   fi
 
-  if [ -z "$2" ]; then
-    >&2 printf "ERROR: remove_permission(): Missing group name!"
-    exit 1
-  fi
+  # Add permission to group.
+  drush php:script --script-path=/opt/genoring/lib genoringapi remove_permission $1
 
-  drush role:perm:remove "$1" "$2"
   if [ $? -gt 0 ]; then
-    >&2 printf "ERROR: Failed to remove permission '$1' from group '$2'!\n"
+    >&2 printf "ERROR: Failed to add permission using YAML file '$1'!\n"
     exit 1
   fi
 }
@@ -679,6 +709,18 @@ case "$cmd" in
   remove_menuitem)
     remove_menuitem "$@"
     ;;
+  add_page)
+    add_page "$@"
+    ;;
+  remove_page)
+    remove_page "$@"
+    ;;
+  add_integration)
+    add_integration "$@"
+    ;;
+  remove_integration)
+    remove_integration "$@"
+    ;;
   add_user)
     add_user "$@"
     ;;
@@ -723,7 +765,7 @@ case "$cmd" in
     ;;
   *)
     if [ ! -z "$1" ]; then
-      >&2 printf "ERROR: Syntax error! Unsupported command '$1'.\n\n"
+      >&2 printf "ERROR: Syntax error! Unsupported command '$cmd $@'.\n\n"
       print_help
       exit 1
     else
